variables:
- group: Build Secrets
- name: zuluLinux08
  value: '/usr/lib/jvm/zulu-8-azure-amd64'
- name: zuluLinux11
  value: '/usr/lib/jvm/zulu-11-azure-amd64'
- name: zuluLinuxLatest
  value: '/usr/lib/jvm/zulu-12-azure-amd64'
- name: openjnine11linux
  value: 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'
- name: openJNineLatestLinux
  value: 'https://api.adoptopenjdk.net/v3/binary/latest/14/ga/linux/x64/jdk/openj9/normal/adoptopenjdk'
trigger:
  batch: true
  branches:
    include:
      - '*'
    exclude:
      - 'dependabot/*'
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - .github/
      - docs/
      - 'benchmark/*.iml'
      - 'betterrandom/*.iml'
      - 'FifoFiller/*.iml'
schedules:
  - cron: "23 0 * * *"
    displayName: Nightly
    branches:
      include:
        - master
    always: true
pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - CHANGELOG.md
      - .submodules
      - .github/
      - docs/
      - 'benchmark/*.iml'
      - 'betterrandom/*.iml'
      - 'FifoFiller/*.iml'
stages:
  - stage: UnitTests
    jobs:
      - job: UnitLinuxPreinstalledZulu
        strategy:
          matrix:
            OpenJdk08:
              PROGUARD: 'true'
              JAVA_HOME: $(zuluLinux08)
              artifactEnvName: OpenJdk08Linux
            OpenJdk11:
              PROGUARD: 'true'
              JAVA_HOME: $(zuluLinux11)
              artifactEnvName: OpenJdk11Linux
            OpenJdkLatest:
              JAVA_HOME: $(zuluLinuxLatest)
              artifactEnvName: OpenJdkLatestLinux
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - template: etc/azureTemplate/unitTestsUbuntu.yml
        - template: etc/azureTemplate/publishCoverage.yml
      - job: UnitLinux
        variables:
          JAVA_HOME: jdk
        strategy:
          matrix:
            OpenJNine11:
              PROGUARD: 'true'
              javaUrl: $(OpenJNine11Linux)
              artifactEnvName: OpenJNine08Linux
            OpenJNineLatest:
              javaUrl: $(OpenJNineLatestLinux)
              artifactEnvName: OpenJNineLatestLinux
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: etc/azureTemplate/installJavaJti.yml
          - template: etc/azureTemplate/unitTestsUbuntu.yml
          - template: etc/azureTemplate/publishCoverage.yml
      - job: UnitMac
        variables:
          JAVA_HOME: jdk
        strategy:
          matrix:
# FIXME: OpenJdk 8 is no longer included in the Mac image; replace with a job that downloads the JDK
#            OpenJdk08:
#              PROGUARD: 'true'
#              javaVersion: 8
#              artifactEnvName: OpenJdk08Mac
            OpenJdk11:
              PROGUARD: 'true'
              javaVersion: 11
              artifactEnvName: OpenJdk11Mac
            OpenJdkLatest:
              javaVersion: 14
              artifactEnvName: OpenJdkLatestMac
        pool:
          vmImage: 'macOs-latest'
        steps:
          - template: etc/azureTemplate/installJavaMacLocal.yml
            parameters:
              javaVersion: $(javaVersion)
          - template: etc/azureTemplate/unitTestsMac.yml
          - template: etc/azureTemplate/publishCoverage.yml
      - job: UnitWindows
        variables:
          artifactEnvName: Windows
        strategy:
          matrix:
            OpenJdk08:
              PROGUARD: 'true'
              JAVA_HOME_SOURCE: JAVA_HOME_8_X64
              artifactEnvName: OpenJdk08Windows
            OpenJdk11:
              PROGUARD: 'true'
              JAVA_HOME_SOURCE: JAVA_HOME_11_X64
              artifactEnvName: OpenJdk11Windows
# FIXME: Replace with a job that downloads the JDK
#            OpenJdkLatest:
#              JAVA_HOME_SOURCE: JAVA_HOME_12_X64
#              artifactEnvName: OpenJdkLatestWindows
        pool:
          vmImage: 'windows-latest'
        steps:
          - powershell: etc/scripts/unit-tests.ps1
            displayName: Build & Test
            failOnStderr: false
            env:
              RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
              JAVA_HOME_SOURCE: $(JAVA_HOME_SOURCE)
          - template: etc/azureTemplate/publishCoverage.yml
  - stage: Mutation
    dependsOn: UnitTests
    jobs:
    - job: Mutation
      variables:
        JAVA_HOME: $(zuluLinuxLatest)
      timeoutInMinutes: 120 # FIXME: Remove once reliably passing in 50
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/installHaveged.yml
        - script: ./etc/scripts/mutation.sh
          displayName: Build & Run Mutation Tests
          env:
            RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
            JAVA_HOME: $(zuluLinux11)
        - task: PublishBuildArtifacts@1
          displayName: Publish Mutation Report
          inputs:
            pathtoPublish: betterrandom/target/pit-reports
            artifactName: Mutation Coverage
  - stage: Benchmarks
    dependsOn: UnitTests
    jobs:
    - job: BenchmarkLinuxPreinstalledZulu
      timeoutInMinutes: 80
      strategy:
        matrix:
          OpenJdk08:
            PROGUARD: 'true'
            JAVA_HOME: $(zuluLinux08)
            artifactEnvName: 'OpenJDK08Linux'
          OpenJdk11:
            PROGUARD: 'true'
            JAVA_HOME: $(zuluLinux11)
            artifactEnvName: 'OpenJdk11Linux'
          OpenJdkLatest:
            JAVA_HOME: $(zuluLinuxLatest)
            artifactEnvName: 'OpenJDKLatestLinux'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/benchmark.yml
    - job: BenchmarkLinux
      timeoutInMinutes: 80
      variables:
        JAVA_HOME: jdk
      strategy:
        matrix:
          OpenJNine11:
            PROGUARD: 'true'
            javaUrl: $(OpenJNine11Linux)
            artifactEnvName: 'OpenJNine11Linux'
          OpenJNineLatest:
            javaUrl: $(OpenJNineLatestLinux)
            artifactEnvName: 'OpenJNineLatestLinux'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/installJavaJti.yml
        - template: etc/azureTemplate/benchmark.yml
    - job: BenchmarkMac
      timeoutInMinutes: 80
      variables:
        artifactEnvName: OpenJdkMac
        JAVA_HOME: jdk
      strategy:
        matrix:
# FIXME: OpenJdk 8 is no longer included in the Mac image; replace with a job that downloads the JDK
#          OpenJdk08:
#            artifactEnvName: 'OpenJdk08Mac'
#            PROGUARD: 'true'
#            javaVersion: 8
          OpenJdk11:
            PROGUARD: 'true'
            artifactEnvName: 'OpenJdk11Mac'
            javaVersion: 11
          OpenJdkLatest:
            artifactEnvName: 'OpenJdkLatestMac'
            javaVersion: 14
      pool:
        vmImage: 'macOs-latest'
      steps:
        - template: etc/azureTemplate/installJavaMacLocal.yml
          parameters:
            javaVersion: $(javaVersion)
        - template: etc/azureTemplate/benchmark.yml
          parameters:
            whichJavaHome: JAVA_HOME_$(javaVersion)_X64
    - job: BenchmarkWindows
      timeoutInMinutes: 80
      pool:
        vmImage: 'windows-latest'
      strategy:
        matrix:
          OpenJdk08:
            PROGUARD: 'true'
            JAVA_HOME_SOURCE: JAVA_HOME_8_X64
            artifactEnvName: 'OpenJdk08Windows'
# FIXME: Fails to launch; see etc/scripts/benchmark.ps1 for details
#          OpenJdk11:
#            JAVA_HOME_SOURCE: JAVA_HOME_11_X64
#            artifactEnvName: 'OpenJdk11Windows'
# FIXME: Replace with a job that downloads the JDK
#          OpenJdkLatest:
#            JAVA_HOME_SOURCE: JAVA_HOME_12_X64
#            artifactEnvName: 'OpenJdkLatestWindows'
      steps:
        - task: PowerShell@2
          displayName: Build & Benchmark
          inputs:
            filePath: etc/scripts/benchmark.ps1
            failOnStderr: false
          env:
            JAVA_HOME_SOURCE: $(JAVA_HOME_SOURCE)
            RANDOM_DOT_ORG_KEY: $(RANDOM_DOT_ORG_KEY)
        - template: etc/azureTemplate/publishBenchmark.yml
  - stage: Dieharder
    dependsOn: UnitTests
    jobs:
    - job: Dieharder
      timeoutInMinutes: 90
      variables:
        javaUrl: $(OpenJNineLatestLinux)
        JAVA_HOME: jdk
      strategy:
        matrix:
          AesCounterRandom:
            class: AesCounterRandom
          Cmwc4096Random:
            class: Cmwc4096Random
          MersenneTwisterRandom:
            class: MersenneTwisterRandom
          XorShiftRandom:
            class: XorShiftRandom
          Pcg128Random:
            class: Pcg128Random
          Pcg64Random:
            class: Pcg64Random
          SingleThreadSplittableRandomAdapter:
            class: 'adapter.SingleThreadSplittableRandomAdapter'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - template: etc/azureTemplate/installJavaJti.yml
        - script: sudo apt install dieharder
          displayName: Install DieHarder
        - script: ./etc/scripts/dieharder.sh
          displayName: Build BetterRandom & Run DieHarder Tests
          env:
            CLASS: $(class)
          failOnStderr: false
        - task: PublishBuildArtifacts@1
          displayName: Publish Report
          inputs:
            pathtoPublish: dieharder.txt
            artifactName: DieHarder Randomness Tests - $(class)
